### ISSUE TITLE
Infinite loop in spread the word

### ISSUE THREAD

**Issue by rebornix** [derjayjay/homebridge-keylights#33]
It's definitely an issue in module `stw` but not sure how it's being triggered 

```
(node:2263) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:54:13)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
    at RecordRegistry.tracePTR (/homebridge/node_modules/homebridge-keylights/node_modules/spread-the-word/dist/RecordRegistry.js:59:57)
```

Fix should go to upstream but the module seems not maintained anymore.

**Comment by derjayjay** [comment]
Hmm, seems like it. I'll have a look.

**Comment by sirkirby** [comment]
Though this issue is a little older, it's just now affecting me as well. Are there any workarounds? Thank you.

**Comment by derjayjay** [comment]
Issue should be resolved now, since stw has been replaced with bonjour-service in the latest release.
